server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Zc123+
  application:
    name: service-provide #将来作为微服务名称
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  type-aliases-package: com.zc.service.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

